### ISSUE TITLE
State flips state between "home" "unknown" and "unavailable" for items (AirTag)

### ISSUE THREAD

**Issue by nonnos** [muehlt/home-assistant-findmy#2] opened 2023-04-08 15:27 UTC
The script works fine for devices but for items, an AirTag to be specific the state changes fast between "home", "unknown" and "unavailable".

Maybe not related to the script due to the state continues to change even after the script is killed!? Need to restart home assistant to get it to stop.

Dump from MQTT:
```
homeassistant/device_tracker/hasses_airtag/config {"name": "Hasses AirTag", "unique_id": "hasses_airtag", "state_topic": "homeassistant/device_tracker/hasses_airtag/state", "json_attributes_topic": "homeassistant/device_tracker/hasses_airtag/attributes", "device": {"identifiers": "hasses_airtag", "manufacturer": "Apple", "name": "Hasses AirTag"}, "source_type": "gps", "payload_home": "home", "payload_not_home": "not_home"}
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state unavailable
homeassistant/device_tracker/hasses_airtag/state unavailable
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state unavailable
XXXXXXXXXXXXXX
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state unavailable
homeassistant/device_tracker/hasses_airtag/state unavailable
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state unavailable
homeassistant/device_tracker/hasses_airtag/state unavailable
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/jonas_iphone_12_pro_max_2/state home
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state unknown
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state home
homeassistant/device_tracker/hasses_airtag/state unavailable
homeassistant/device_tracker/hasses_airtag/state unavailable
```

**Comment by muehlt** [comment] 2023-04-12 21:18
I can't reproduce this, but as you said, it may not be caused (just) by the script. However, I have some updates pending locally that take some of the load off the home assistant instance, among other things. Maybe that helps with this issue - unfortunately, I am not sure when I'll find the time to prepare and test the update - was this just a one-time error, or is the script unusable this way for you?

Btw, I removed your location info from the original message and purged the edit history, but please check again if everything is gone that you might not have wanted to share with us :)

**Comment by muehlt** [comment] 2023-08-11 15:04
@nonnos, thank you for your patience! Could you test if [v1.0.2](https://github.com/muehlt/home-assistant-findmy/blob/main/.github/MIGRATION_GUIDE/1.0.2.md) resolves the issue you encountered? As I mentioned in my previous comment, I suspect your instance might have been overwhelmed by frequent state updates. The latest version of the script has been modified to minimize state publications. You can now easily [install it using pip](https://github.com/muehlt/home-assistant-findmy/blob/main/.github/MIGRATION_GUIDE/1.0.2.md).

**Comment by muehlt** [comment] 2023-11-02 13:10
I'm closing the issue since I think [v1.0.2](https://github.com/muehlt/home-assistant-findmy/blob/main/.github/MIGRATION_GUIDE/1.0.2.md) should have resolved the problems or the issue is not related to the script, but please let me know if you are still having issues with the newest release.

**Closed by muehlt** 2023-11-02 13:10 UTC
